### ISSUE TITLE
Question about the vocab size ?

### ISSUE THREAD

**Issue by pengshuang** [ddddwy/Reinforce-PG#1]
I think 5000 is too small. Do I need to increase vocab size ?

https://github.com/wyu-du/Reinforce-Paraphrase-Generation/blob/7c788fd5d70ca4bee9c49db86692ec50f8df2530/src/config.py#L29

**Comment by wyu-du** [comment]
> I think 5000 is too small. Do I need to increase vocab size ?
> 
> https://github.com/wyu-du/Reinforce-Paraphrase-Generation/blob/7c788fd5d70ca4bee9c49db86692ec50f8df2530/src/config.py#L29

You don't have to, because the decoder is a pointer network, it will copy the out-of-vocabulary word from the input sentence when generating the output paraphrase.

You may refer to this paper for the pointer network: https://arxiv.org/pdf/1704.04368.pdf

**Comment by pengshuang** [comment]
Much thanks ！
