### ISSUE TITLE
How to preprocess the data?

### ISSUE THREAD

**Issue by Xiao0728** [ddddwy/Reinforce-PG#4]
Hi, 
How to preprocess a user's dataset, to get the chunked data?
Thanks, 
Xiao

**Comment by wyu-du** [comment]
Hi Xiao,

I preprocess the chunked data using this [script](https://github.com/abisee/cnn-dailymail).

Best,
Wanyu

**Comment by Xiao0728** [comment]
Hi Wanyu,
Thanks for the reply, very helpful.
Xiao
