### ISSUE TITLE
GPU利用率低

### ISSUE THREAD

**Issue by googlx** [ddddwy/Reinforce-PG#5]
首先，感谢作者大大的杰出贡献。

但是运行代码的过程中，GPU占用率总是在10%+到30%之间跳动，即使将batch size设置为128也不管用。请问这可能是什么的原因？谢谢！

**Comment by wyu-du** [comment]
谢谢你对我们的工作感兴趣！

我认为GPU占用率低的问题可能是因为在training过程中需要decode prediction来计算RL Reward。具体请参照这段代码：https://github.com/wyu-du/Reinforce-Paraphrase-Generation/blob/7c788fd5d70ca4bee9c49db86692ec50f8df2530/src/train_util.py#L60

希望对你有帮助，谢谢！

**Comment by googlx** [comment]
谢谢，您的回答很有帮助
