### ISSUE TITLE
Dependencies for the code.

### ISSUE THREAD

**Issue by Xiao0728** [ddddwy/Reinforce-PG#6]
Hi,
Could you specify what dependencies could be used for the code? or where I can find them? e.g. The version number. Thanks very much.

Xiao

**Comment by songbohu** [comment]
> Hi,
> Could you specify what dependencies could be used for the code? or where I can find them? e.g. The version number. Thanks very much.
> 
> Xiao

Hi Xiao,

Do you know the requirements for this code?

Thanks

Songbo

**Comment by Xiao0728** [comment]
> Hi Xiao,
> 
> Do you know the requirements for this code?
> 
> Thanks
> 
> Songbo

Sorry, haven't got a reply from the authors yet.
